apiVersion: v1
kind: Secret
metadata:
  namespace: ingress-nginx
  name: app-secret
data:
  MYSQL_DATABASE_USER: "cm9vdA=="
  MYSQL_DATABASE_PASSWORD: "cm9vdA=="
  MYSQL_DATABASE_DB: "QnVja2V0TGlzdA=="
  MYSQL_DATABASE_HOST: "db-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: Db-secret
  namespace: ingress-nginx
data:
  MYSQL_ROOT_PASSWORD: "cm9vdA=="
