apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{.Values.clusterissuer.name}}
spec:
  acme:
    server: {{ .Values.clusterissuer.server }}
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.name }}-private-key
    solvers:
      - http01:
          ingress:
            class: {{.Values.ingress.class}}
