---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
      - name: {{.Values.app.Docker_secret}}
      containers:
      - image: {{.Values.app.image.name}}:{{.Values.app.image.tag}}
        name: app
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
        ports:
        - containerPort: 9090
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlCredentials
              key: {{ .Values.DB.password | b64enc}}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: DB-credentials
              key: {{ .Values.DB.username | b64enc}}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: DB-credentials
              key: password
        - name: MYSQL_DATABASE
          value: "inernship"
            
