---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
      - name: {{.Values.app.Docker_secret}}
      containers:
      - image: {{.Values.app.image.repo_app}}:{{.Values.app.image.tag_app}}
        name: app
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
        ports:
        - containerPort: 9090
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.DB.password }}
        - name: MYSQL_USER
          value: {{ .Values.DB.username }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.DB.password }}
        - name: MYSQL_DATABASE
          value: "inernship"
            
