---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      imagePullSecrets:
      - name: {{.Values.app.Docker_secret}}
      containers:
      - image: {{.Values.app.image.repo_app}}:{{.Values.app.image.tag_app}}
        name: app
        ports:
        - containerPort: {{.Values.app.containerport}}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{.Values.app.containerport}}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{.Values.app.containerport}}
          initialDelaySeconds: 10
          periodSeconds: 15
        env: {{ .Values.app.env | toYaml | nindent 8 }}
  
