apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: {{ .Values.DB.username | b64enc}}
  password: {{ .Values.DB.password | b64enc}}
  root_password: {{ .Values.DB.root_password | b64enc}}
  
