---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.DB.name}}-headless
spec:
  clusterIP: None
  selector:
    app: {{.Values.DB.name}}
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-svc
  labels:
    app: {{.Values.app.name}}-svc
spec: 
  selector:
    app: {{.Values.app.name}} 
  ports:
  - port: {{.Values.app.serviceport}}
    targetPort: {{ .Values.app.containerport }}
    
  