apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{.Values.DB.name}}
  name: {{.Values.DB.name}}
spec:
  replicas: {{.Values.DB.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.DB.name}}
  serviceName: {{.Values.DB.name}}-headless
  template:
    metadata:
      labels:
        app: {{.Values.DB.name}}
    spec:
      containers:
      - image: {{.Values.DB.image.name}}:{{.Values.DB.image.tag}}
        name: {{.Values.DB.name}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.DB.password }}

        - name: MYSQL_USER
          value: {{ .Values.DB.username }}

        - name: MYSQL_PASSWORD
          value: {{ .Values.DB.password }}
                
        - name:  MYSQL_DATABASE
          value: "internship"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: {{.Values.DB.volumeclaimtemplates.name}}
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: {{.Values.DB.volumeclaimtemplates.name}}
    spec:
      accessModes: 
      - {{.Values.storageclass.accessmodes}}
      storageClassName: {{.Values.storageclass.name}}
      resources:
        requests:
          storage: {{.Values.storageclass.storage}}