apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd # Change to your ArgoCD namespace if different
spec:
  project: default # Change to your desired project
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 0.18.1
    helm:
      parameters:
        - name: controller.replicaCount
          value: "2"  # Change this value to your desired replica count
        - name: controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"
          value: "nlb"  # Use "alb" for AWS ALB

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # to create a NameSpace if it doesn't exists
    automated: {}

