- name: Install and configure Jenkins
  hosts: jenkins
  
  vars:
    - username: admin1
    - password: admin1

  tasks:
    - name: Add Jenkins GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        validate_certs: no
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
        state: present

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: daemon-reload
      systemd:
        daemon_reload: true

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Download Jenkins CLI jar
      get_url:
        url: http://localhost:8080/jnlpJars/jenkins-cli.jar
        dest: /home/ec2-user
      register: cli_installed

    # - name: Create Jenkins user
    #   command:
    #     cmd: 'echo ''jenkins.model.Jenkins.instance.securityRealm.createAccount("{{ username }}", "{{ password }}")'' | java -jar ./jenkins-cli.jar -s "http://localhost:8080" -auth admin:$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword) -noKeyAuth groovy = -'
    #     chdir: /home/ubuntu
    #     creates: /home/ubuntu/somedir/somelog.txt

    

    - name: Get Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_admin_password

    - name: Set Jenkins initial admin password
      set_fact:
        jenkins_initial_admin_password_decoded: "{{ jenkins_initial_admin_password['content'] | b64decode }}"

    - name: Create Jenkins user
      shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("{{ username }}", "{{ password }}")' |java -jar ./jenkins-cli.jar -s "http://localhost:8080" -auth admin:$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword) -noKeyAuth groovy = –
      args:
        chdir: /home/ubuntu

    - name: Install Suggested Plugins
      jenkins_plugin:
        name: suggested
        state: present
        url_username: "{{ username }}"
        url_password: "{{ password }}"
        url: "http://localhost:8080"
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          Jenkins-Crumb: '{{ lookup(''url'', ''http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'') }}'
    
    
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted      
