app:
  name: go-app
  replicaCount: 2
  minreplicas: 1
  maxreplicas: 3
  average_utilization: 70
  image:
    repo_app: 889149267524.dkr.ecr.us-east-1.amazonaws.com/go_app
    tag_app: 1.0.0-3
  containerport: "9090"
  serviceport: "80"
  Docker_secret: ecr-secret


DB:
  replicaCount: 2
  minreplicas: 1
  maxreplicas: 3
  average_utilization: 70
  name: mysql
  image:
    name: mysql
    tag: "8.0"
  volumeclaimtemplates:
    name: mysqldb
  username: m3del
  password: p@ssw0rd
  containerport: "3306"
  serviceport: "3306"

storageclass:
  name: "ebs-storage"
  accessmodes: ReadWriteOnce
  storage: 1Gi